### PR TITLE
Management API supports sorting distributionset by "createdAt" #687

### LINKED ISSUE #687: Management API supports sorting distributionset by "createdAt"
When executing the REST call to the Hawkbit Management API
`rest/v1/distributionsets?sort=createdAt%3ADESC`
I get the following response: 400 Bad Request
```
{
    "exceptionClass": "org.eclipse.hawkbit.rest.exception.SortParameterUnsupportedFieldException",
    "errorCode": "hawkbit.server.error.rest.param.invalidField",
    "message": "The given sort parameter field does not exist"
}
```
However, a similar call succeeds:
`rest/v1/distributionsets?sort=id%3ADESC`
Result is: 200 ok.

P.S: I have also tried `created_at`, `createdat`. Without success.

### PR DESCRIPTION
**Pull request by laverman**
Fixes #687 

Signed-off-by: Jeroen Laverman <jeroen.laverman@bosch-si.com>

### CODE REVIEW

File: hawkbit-core/src/main/java/org/eclipse/hawkbit/repository/DistributionSetFields.java [hunk 1]
```diff
@@ -25,6 +25,14 @@
      * The description field.
      */
     DESCRIPTION("description"),
+    /**
+     * The createdAt field.
+     */
+    CREATEDAT("createdAt"),
```
Comment (stefbehl) [inline hawkbit-core/src/main/java/org/eclipse/hawkbit/repository/DistributionSetFields.java]: I'd prefer "CREATED_AT" and "LAST_MODIFIED_AT"

Comment (laverman) [reply hawkbit-core/src/main/java/org/eclipse/hawkbit/repository/DistributionSetFields.java]: While I agree, that it would improve readability, it would be inconsistent with the other field enums (cf. TargetFields).

Comment (stefbehl) [reply hawkbit-core/src/main/java/org/eclipse/hawkbit/repository/DistributionSetFields.java]: Ok, makes sense... thanks!
